### ISSUE TITLE
个人认为,mdx资源独立出来比较好

### ISSUE THREAD

**Issue by lujun9972** [ninja33/mdx-server#1]
因为mdx-server本身与mdx资源是分离的,不相关的.
而且我在clone仓库的时候巨慢,毕竟要把mdx文件也clone下载

**Comment by ninja33** [comment]
不会的。
.gitignore 文件里已经把.mdx 和.mdd 排除了。

**Comment by lujun9972** [comment]
然而事实是,你确实把mdx和mdd文件传上github了...

**Comment by ninja33** [comment]
嗯，因为那个是编辑.gitignore后，通过github网页上传的词典。
现在已经把词典文件去掉了。
