### ISSUE TITLE
单词大小写敏感

### ISSUE THREAD

**Issue by lujun9972** [ninja33/mdx-server#2]
比如使用牛津词典时,查Race是没有结果的,而必须是race才能查到.

可否改成大小写不敏感?

**Comment by ninja33** [comment]
这个问题，在goldendict这类词典程序里也是这样的，如果词头(head word)不符合要求，就是查不出来的。除了大小写，外部程序在调用前，还应该去除复数，过去式，现在分词等等对单词造成的形变。

去除形变不是server的功能，而是外部程序应该做的。mdx server只是原样提供mdx 文件内的信息，不会做任何定制化和预处理。原则上应该是你的Emacs插件来处理这件事。 :smile:

**Comment by lujun9972** [comment]
这件事情,外部程序还真的做不到....
