### ISSUE TITLE
字典文件

### ISSUE THREAD

**Issue by mgcyung** [ninja33/mdx-server#5]
在哪可以找到manual里列出的字典文件?

**Comment by ninja33** [comment]
please Google mdx file

**Comment by mgcyung** [comment]
ninja huang <notifications@github.com> writes:

> please Google mdx file
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

字典的好坏直接影响使用体验，如果使用词意解释不全的字典，可能在使用该软件
查询后，还需查询其它词典作为补充，这样会降低使用体验。google mdx file的
结果大多是怎么读写mdx格式，好的字典文件自然不容易被google到。manual中
给出的字典文件质量都很高，不知能否分享

**Comment by mgcyung** [comment]
可参考mdx词库制作交流论坛
